name: dart_mqtt_broker
description: A MQTT Broker written in dart
version: 1.0.3
repository: https://github.com/elrizwiraswara/dart_mqtt_broker

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
